---
- hosts: all
  connection: local
  gather_facts: no
  
  tasks:
  - name: Obter informações dos dispositivos
    cisco.ios.ios_facts:
  
  - name: create a backup
    cisco.ios.ios_config:
      backup: yes
      backup_options: 

      
