---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Going to merge change.txt to running-config
    ios_config:
      diff_against: running
      src: /etc/ansible/backup/CISCOLAB_config.2023-05-18@20:42:57
    register: test_diff
  
  - name: the only config we need to merge is
    debug:
      var: test_diff.updates

  - name: Going to merge change.txt to startup-config
    ios_config:
      diff_against: startup
      src: /etc/ansible/backup/CISCOLAB_config.2023-05-18@20:42:57
    register: test_diff2
  
  - name: the only startup-config we need to merge is
    debug:
      var: test_diff2.updates
