download_url: https://galaxy.ansible.com/download/cisco-ios-4.5.0.tar.gz
format_version: 1.0.0
name: ios
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 4.5.0
version_url: https://galaxy.ansible.com/api/v2/collections/cisco/ios/versions/4.5.0/
